[project]
name = "stateflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
authors = [
  { name = "Andreas Nachtmann", email = "virtualnonsense@mailbox.org" },
]
dependencies = []

[project.urls]
Documentation = "https://github.com/virtualnonsense/stateflow#readme"
Issues = "https://github.com/virtualnonsense/stateflow/issues"
Source = "https://github.com/virtualnonsense/stateflow"

[dependency-groups]
dev = [
  "pytest>=9.1.1",
]

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
